### ISSUE TITLE
unrelated concepts in task description and example data

### ISSUE THREAD

**Issue by ftyers** [dpaperno/DiscriminAtt#1]
In the task description it is stated, "... detecting the difference between two unrelated concepts, such as a narwhal and a tractor, would not constitute a very interesting task."

But then in the trial data you have:
```
fawn,blouse,fast,1
fawn,blouse,leaves,1
fawn,blouse,spots,1
fawn,blouse,eats,1
fawn,blouse,small,1
fawn,blouse,grass,1
fawn,blouse,tail,1
fawn,coat,fast,1
fawn,coat,leaves,1
fawn,coat,spots,1
```
Is the test data going to include these kind of incomparable concepts ?

**Comment by dpaperno** [comment]
Thank you for pointing this out! This is not an issue after all.

The point is that if most concept pairs were unrelated, the task becomes too simple, almost uninteresting. So we made sure that most word pairs in our data are indeed related, but we also included some unrelated word pairs for control.
