### ISSUE TITLE
Open / closed competition?

### ISSUE THREAD

**Issue by ftyers** [dpaperno/DiscriminAtt#3]
Is it possible to use external data sources (externally-trained embeddings, Wikipedia, parsing/processing) or should we just train on the data available here ?

**Comment by dpaperno** [comment]
This is a very important question. Thank you for posting it here. 

We have updated the participate tab of the competition website on CodaLab with the following clarification:

We expect that a successful system will rely on existing linguistic resources. We don't know in advance which resource or which combination of resources is best to be used for our task. Your system can use any **resources created automatically** (e.g. corpora of naturally occurring texts, word embeddings, knowledge graphs) **or by aggregating expert knowledge** (e.g. WordNet, FrameNet or other lexicographic resources).

However, you are **not allowed** to use resources derived from _data elicitation_ from human subjects, such as free association norms, feature norms, relatedness judgements, priming effect data etc.
