### ISSUE TITLE
UnboundLocalError in evaluation.py 

### ISSUE THREAD

**Issue by omidrohanian** [dpaperno/DiscriminAtt#4]
In the evaluation file, `f1_positives `and `f1_negatives` are defined within conditionals. I think it is better if they are initialized beforehand as this might cause UnboundLocalError on line 31. Those conditions cannot both hold true all the time (e.g. a system that produces zero true positives but a lot of true negatives).

**Comment by dpaperno** [comment]
Thank you Omid, we have fixed this following your suggestion!
